main:
  - name: Home
    url: /#top
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30 
  - name: News & Events
    url: event/
    weight: 40
  - name: Gallery
    url: gallery/
    weight: 50
  - name: Members
    url: people/
    weight: 60 
  - name: Opportunities
    url: positions/
    weight: 70 
  - name: Contact Us
    url: /#contact
    weight: 80
