main:
  - name: Research
    url: /#research
    weight: 10
  - name: Publications
    url: publication/
    weight: 20 
  - name: News & Events
    url: event/
    weight: 30
  - name: Gallery
    url: gallery/
    weight: 40
  - name: Members
    url: people/
    weight: 50 
  - name: Opportunities
    url: positions/
    weight: 60 
  - name: Contact Us
    url: /#contact
    weight: 70
