main:
  - name: Home
    url: /#top
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30 
  - name: News & Events
    url: event/
    weight: 40
  - name: Gallery
    url: gallery/
    weight: 50
  - name: Members
    url: /#members
    weight: 60 
  - name: Opportunities
    weight: 70
    hasChildren: true
  - parent: Opportunities
    name: Positions
    url: /#positions
  - parent: Opportunities
    name: Funding Opportunities
    url: funding/
  - name: Contact
    url: /#contact
    weight: 80
